# prerequisites:
 ### Python 
 ### NumPy


# Scalars, Vectors, Matrices, and Tensors
### Scalar: a single number or value.
### Vector: a 1_D array of numbers.
### Matrix: a 2_D array of numbers. 
### Tensor: in general an array of numbers with a variable of axes is known as a tensor.


In [1]:
import numpy as np

#defining a scalar
x = 5
print('x = {} is a scalar'.format(x))

#defining a vector
x = np.array([1,2,3,4])
print('x : {} is a vector (1_D array) with shape {} and size = {}'.format(x, x.shape, x.size))

#defining a matrix
x = np.array([[1,2],[3,4],[5,6]])
print('x is a matrix (2_D array) with shape {} and size = {} :'.format(x.shape, x.size))
print(x)

#another definition of matrix
# x=np.matrix([[1,2],[3,4],[5,6]])
# print(x)

x = 5 is a scalar
x : [1 2 3 4] is a vector (1_D array) with shape (4,) and size = 4
x is a matrix (2_D array) with shape (3, 2) and size = 6 :
[[1 2]
 [3 4]
 [5 6]]


### Define a  matrix and a tensor of given dimention

In [2]:
x = np.ones((3,3))
print(x)
print(' Matrix dimention is : {} and matrix size is : {}'.format(x.shape, x.size))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
 Matrix dimention is : (3, 3) and matrix size is : 9


In [3]:
x = np.ones((3,3,3))
print(x)
print(' Tensor dimention is : {} and tensor size is : {}'.format(x.shape, x.size))

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
 Tensor dimention is : (3, 3, 3) and tensor size is : 27


### Note: Indexing starts at 0


In [4]:
A = np.ones((5,5), dtype = np.int)
print(A)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [5]:
A[0,1] = 2
print(A)

[[1 2 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [6]:
A[:, 0] = 3
print(A)

[[3 2 1 1 1]
 [3 1 1 1 1]
 [3 1 1 1 1]
 [3 1 1 1 1]
 [3 1 1 1 1]]


In [7]:
A[: , :] = 5
print(A)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [8]:
#for higher dimensions, simply add an index
A = np.ones((5,5,5), dtype = np.int)
# print(A)

#assigne first row a new value
A[:,0,0] = 3
print(A)

[[[3 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[3 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[3 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[3 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[3 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


### Matrix operations 


In [9]:
A = np.array([[1,2],[3,4]])
print(A)

[[1 2]
 [3 4]]


In [10]:
B = np.ones((2,2), dtype=np.int)
print(B)

[[1 1]
 [1 1]]


In [11]:
# Element wise sum
C = A + B
print(C)

[[2 3]
 [4 5]]


In [12]:
# Element wise subtraction
C = A - B
print(C)

[[0 1]
 [2 3]]


In [13]:
# matrix multiplication
C = A * B
print(C)

[[1 2]
 [3 4]]


### Transpose: an operator which flips a matrix over its main diagonal. The incides of the rows and columns are switched. 

In [14]:
# the matrix transpose
A = np.array(range(9))
# A = np.arange(9)
A = A.reshape(3,3)
print(A)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [15]:
B = A.T
print(B)

[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [16]:
A = np.array(range(10))
A = A.reshape((2,5))
print(A)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [17]:
B = A.T
print(B)

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [18]:
# tensors
A = np.ones((3,3,3,3,3,3,3,3,3,3))
# print(A)
print(A.shape)
print(len(A.shape))
print(A.size)

(3, 3, 3, 3, 3, 3, 3, 3, 3, 3)
10
59049


# Vector and Matrix Norms 

In [19]:
u = np.array([1, 2])
# print(u)

v = np.array([3, 4])
# print(v)

print(u+v)
print(np.linalg.norm(u+v))

[4 6]
7.211102550927978


### Note: ||u+v||<=||u||+||v||

In [20]:
print(np.linalg.norm(u)+np.linalg.norm(v))

7.23606797749979


### The $L^p$ Norms 
### In general: $||x||_p = (\sum_i |x_i|^p)^{1/p}$
### Notes:
### * $L^0$ shows the number of non_zero elements in a vector.
### * $L^1$:  $||x||_1 = \sum_i |x_i|$
### * $L^2$ (Euclidean norm): $||x||_2 = (\sum_i|x_i|^2)^{1/2}$
### * $L^{\infty}$: $||x||_i = max_i |x_i|$

### Squared Euclidean Norm of matrix x is calculated by $x^Tx$ operation:


In [21]:
x = np.array([[2], [5], [3], [3]])
euclideanNorm = x.T.dot(x)
print(euclideanNorm)

[[47]]


### Matrix norm
### Frobenius form: $||A||_F = \sqrt(\sum_{i,j}A_{i,j}^2)$

In [22]:
A = np.array([[1,2],[3,4],[5,6]])
print(np.linalg.norm(A))

9.539392014169456
