# 1- Numpy
**NumPy** (stands for Numerical Python) is the fundamental library for scientific computing with Python. We use this packages to work with **matrices** (n_D arrays). Matrices are so important in **Machine Learning**, since they are used to reading and representing **Inputs, Outputs, and Parameters**.

In [1]:
#import the numpy packages to be able to use it.
import numpy as np
!python --version

Python 3.7.4


In [2]:
#Seeing all defined functions and variables in numpy 
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '

# 1-1. Creating Arrays in Numpy
The main **object** of Numpy is the multidimensional array(In Numpy **dimensions** are called **axes**).The array class of Numpy is called **ndarray** (array). We can creat n_D arrays (such as vectors or matrices) using following commands:

In [3]:
# create a vector as a Row
a = np.array([1,2,3])
print('a is a Row vector : ',a, '\n')

# create a vector as a Column
b = np.array([[1],[2],[3]])
print('b is a Column vector : \n',b)

a is a Row vector :  [1 2 3] 

b is a Column vector : 
 [[1]
 [2]
 [3]]


The more important **attributes** of an **ndarray** object are:<br></br><br></br>
 <li>**ndarray.ndim:** the number of dimentions of the array. </li><br></br>
 <li>**ndarray.shape:** a tuple of integers indicating the size of the array in each dimension.</li><br></br>
 <li>**ndarray.size:** the total number of elements of the array.</li><br></br>
 <li>**ndarray.dtype:** the type of the elements in the array.</li><br></br>
 <li>**ndarray.itemsize:** the size in bytes of each element of the array.</li><br></br>

In [4]:
np.shape(a)
#or
#print(a.shape)

(3,)

In [5]:
# the following two commands show you the Docstring of every variables and functions in NumPy 
help(np.shape)
# Or
np.shape?

Help on function shape in module numpy:

shape(a)
    Return the shape of an array.
    
    Parameters
    ----------
    a : array_like
        Input array.
    
    Returns
    -------
    shape : tuple of ints
        The elements of the shape tuple give the lengths of the
        corresponding array dimensions.
    
    See Also
    --------
    alen
    ndarray.shape : Equivalent array method.
    
    Examples
    --------
    >>> np.shape(np.eye(3))
    (3, 3)
    >>> np.shape([[1, 2]])
    (1, 2)
    >>> np.shape([0])
    (1,)
    >>> np.shape(0)
    ()
    
    >>> a = np.array([(1, 2), (3, 4)], dtype=[('x', 'i4'), ('y', 'i4')])
    >>> np.shape(a)
    (2,)
    >>> a.shape
    (2,)



In [6]:
 a = np.array([[1, 2], [3, 4]])
print(a)

[[1 2]
 [3 4]]


In [7]:
a.shape

(2, 2)

In [8]:
print(np.shape(np.array([1,2,3])))

(3,)


In [9]:
b = np.array([[1,2,3],[4,5,6]])
print(b,'\n')
print(b.shape)

[[1 2 3]
 [4 5 6]] 

(2, 3)


**Note**<br></br> <li>**reshape:** gives a new shape to an array without changing its data (size of array does not change).</li><br></br> <li>**resize:** changes shape and size of array in-place..</li>

In [10]:
print(b.shape, '\n')
np.reshape(b,(3,2))

(2, 3) 



array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:
print(b.shape)

(2, 3)


In [12]:
print(b)

[[1 2 3]
 [4 5 6]]


In [13]:
np.resize(b,(3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
# notice that (4,4) is larger than the shape of original array, 
# then the new array is filled with repeated copies of `b`
np.resize(b,(4,4)) 

array([[1, 2, 3, 4],
       [5, 6, 1, 2],
       [3, 4, 5, 6],
       [1, 2, 3, 4]])

In [15]:
# notice that (4,4) is larger than the shape of original array, 
# then the new array is filled with zeros instead of repeated copies of `y`
y = np.array([[0, 1], [2, 3]])
y.resize(4,4)
print(y)

[[0 1 2 3]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


**Two ways to convert 1_D array to 2_D array:**

In [16]:
x = np.array([1,2,3])
print(x)
print(type(x))

[1 2 3]
<class 'numpy.ndarray'>


In [17]:
print(x[:,np.newaxis]) # or print(x[: , None])


[[1]
 [2]
 [3]]


In [18]:
print(np.shape([[1,2,3],[4,5,6]]))

(2, 3)


**Numpy** also provides many functions to create arrays. see following examples:

In [19]:
# create an array of zeros
a = np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [20]:
# create an array of ones
b = np.ones((3,3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [21]:
#create a constant array
c = np.full((3,3),5)
print(c)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [22]:
# create an identity matrix
d = np.eye(2)
print(d)

[[1. 0.]
 [0. 1.]]


**Notice that:**<br></br><li>**arange:** returns evenly spaced values within a given interval. For using a non-integer step, such as 0.1, it is better to use **linspace**.</li><br></br> <li>**logspace:** returns numbers spaced evenly on a log scale.</li>

In [23]:
print(np.arange(1,10))

[1 2 3 4 5 6 7 8 9]


In [24]:
print(np.linspace(1, 10))

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [25]:
x = np.logspace(1,5,num=5)
print(x)

[1.e+01 1.e+02 1.e+03 1.e+04 1.e+05]


In [26]:
# for setting printing options.
np.set_printoptions(formatter = {'all': lambda x: '%d' % x})
print(x)

[10 100 1000 10000 100000]


In [27]:
# return to default
np.set_printoptions()
print(x)

[1.e+01 1.e+02 1.e+03 1.e+04 1.e+05]


# 1-2. Access to elements
<br></br><li>**Indexing and Slicing**</li>

# 1-3. Array operations
<br></br><li>**Mathematical and statistical operation**</li>
<br></br><li>**Matrix operation**</li>
See <a href="https://github.com/SarahParsa/Learning-Machine-Learning-in-Python/blob/master/Linear-Algebra%20in%20Machine-Learning%20in%20Python.ipynb"> this topic</a>

# 1-4. Distributions in NumPy 

In this section I want to show the all standard Numpy operations which would be required to start Machine_Learning journey with Python. It will be completed soon ...